apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: baseball-chatbot
spec:
  destination:
    name: ''
    namespace: baseball-prod
    server: 'https://kubernetes.default.svc'
  source:
    path: 'deploy/helm'
    repoURL: 'https://github.com/glroland/baseball-chatbot.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
