apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "baseball-chatbot.fullname" . }}
  labels:
    {{- include "baseball-chatbot.labels" . | nindent 4 }}
immutable: false
data:
  OPENAI_BASEURL: "{{ .Values.global.appconfig.inferenceUrl }}"
  OPENAI_MODEL: "{{ .Values.global.appconfig.inferenceModel }}"
  OPENAI_APIKEY: "nokey"
  TEMP_PRODUCT_DB_CONN_STRING: "host={{ .Release.Name }}-db port=5432 dbname=ai_product_catalog user=baseball-chatbot password=ai_product_catalog123 connect_timeout=30"
  PRODUCT_DB_CONN_STRING: "host=db port=5432 dbname=ai_product_catalog user=baseball-chatbot password=ai_product_catalog123 connect_timeout=30"
  NUM_WORKERS: "5"
