apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "baseball-chatbot.fullname" . }}
  labels:
    {{- include "baseball-chatbot.labels" . | nindent 4 }}
immutable: false
data:
  OPENAI_BASEURL: "http://envision:8321"
  OPENAI_MODEL: "meta-llama/Llama-3.2-11B-Vision-Instruct"
  NUM_WORKERS: "5"
