apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "baseball-chatbot.fullname" . }}
  labels:
    {{- include "baseball-chatbot.labels" . | nindent 4 }}
immutable: false
data:
  DB_CONNECTION_STRING: "postgresql://baseball_app:baseball123@db.home.glroland.com:5432/baseball_db"
