apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "baseball-chatbot.fullname" . }}
  labels:
    {{- include "baseball-chatbot.labels" . | nindent 4 }}
data:
  application.properties: |-
    spring.application.name=baseball-chatbot

    # Default Chat Model

    # Default Model Values (applied to all)
    baseball-chatbot.max-tokens=100
    baseball-chatbot.temperature=0.1
    baseball-chatbot.top-p=1.0
    baseball-chatbot.timeout-seconds=300

    # Embedding Model Configuration
    baseball-chatbot.embedding-model=sentence-transformers/all-mpnet-base-v2
    baseball-chatbot.hf-api-key=${HF_TOKEN}

    # Agent w/Tool Assist Model Configuration 

    # Database Configuration
    spring.datasource.driver-class-name=org.postgresql.Driver
    spring.datasource.username=baseball-chatbot
    spring.datasource.password=ai_product_catalog123
    # spring.datasource.url=jdbc:postgresql://{{ .Release.Name }}-db:5432/ai_product_catalog
    spring.datasource.url=jdbc:postgresql://db:5432/ai_product_catalog

    # File Upload Config
    spring.servlet.multipart.file-size-threshold=2KB
    spring.servlet.multipart.max-file-size=200MB
    spring.servlet.multipart.max-request-size=215MB
    server.connection-timeout=5000

    # Logging Configuration
    logging.level.com.glroland=DEBUG
    langchain4j.open-ai.chat-model.log-requests=true
    langchain4j.open-ai.chat-model.log-responses=true
    logging.level.dev.langchain4j=INFO
    #logging.level.dev.ai4j.openai4j=INFO
    #logging.level.dev.ai4j.mistral=DEBUG
