apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "baseball-chatbot.fullname" . }}
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"{{ .Release.Name }}-log-svc"}]'
  labels:
    app.kubernetes.io/part-of: "{{ .Release.Name }}-baseball-chatbot"
    {{- include "baseball-chatbot.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "baseball-chatbot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "baseball-chatbot.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.global.image.usePullSecret }}
      imagePullSecrets:
      - name: baseball-chatbot-pull-secret
      {{- end }}
      {{ if eq .Values.global.useServiceAccount true }}
      serviceAccountName: {{ include "baseball-chatbot.fullname" . }}
      {{ end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.image.repository }}{{ .Values.image.name }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.image.port }}
          env:
            - name: JAVA_OPTS_APPEND
              value: '-Dlogging.level.root=INFO'
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: HF_TOKEN
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: OPENAI_API_KEY
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /deployments/config
            name: application-properties
            readOnly: true
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.image.port }}
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.image.port }}
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.image.port }}
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - configMap:
          defaultMode: 511
          items:
          - key: application.properties
            path: application.properties
          name: {{ include "baseball-chatbot.fullname" . }}
        name: application-properties
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
